name: Part 1 Workflow

on:
  push:

jobs:

  # Notify Discord server of pipeline starting
  discord-begin:
    runs-on: ubuntu-latest
    steps:
    - name: Discord webhook start notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        username: "the GOAT"
        avatar-url: https://upload.wikimedia.org/wikipedia/commons/d/d3/Deer-Goat.jpg
        embed-title: "Security Pipeline jobs are starting..."
        embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        embed-author-name: "${{ github.triggering_actor }}"

  # Build and push Docker image to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/itas276-assign1:latest .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itas276-assign1:latest

  # SAST with Semgrep
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Clone application source code
        uses: actions/checkout@v4
      - name: Run full Semgrep scan
        run: |
          semgrep \
            --sarif --output semgrep-sast.sarif \
            --metrics=off \
            --config="p/default"
      - name: Save report as pipeline artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif

  # SCA with Snyk
  snyk:
    needs:
      - build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/itas276-assign1:latest
        args: --sarif-file-output=snyk.sarif # Tell snyk to output sarif file
      continue-on-error: true
    - name: Save report as pipeline artifact
      uses: actions/upload-artifact@v4
      with:
        name: snyk-sca.sarif
        path: snyk.sarif

  # Notify Discord server of snyk job
  discord-snyk:
    runs-on: ubuntu-latest
    needs: [snyk]
    steps:
    - name: Download Snyk SARIF report
      uses: actions/download-artifact@v4
      with:
        name: snyk-sca.sarif
    - name: Discord webhook end notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        username: "the GOAT"
        avatar-url: https://upload.wikimedia.org/wikipedia/commons/d/d3/Deer-Goat.jpg
        embed-title: "Snyk SCA completed."
        embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        embed-author-name: "${{ github.triggering_actor }}"
        filename: snyk.sarif 

  # Notify Discord server of pipeline ending
  discord-end:
    runs-on: ubuntu-latest
    needs: [snyk, semgrep]
    if: always()
    steps:
    - name: Discord webhook end notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        username: "the GOAT"
        avatar-url: https://upload.wikimedia.org/wikipedia/commons/d/d3/Deer-Goat.jpg
        embed-title: "Security Pipeline jobs have completed!"
        embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        embed-author-name: "${{ github.triggering_actor }}"
